name: Analyseroom
description: That's our final paper to be certificated in IT on IFF. Basically it's a door unlocking with digital system build on Arduino Mega (2560) and futhermore there's a mobile app build with flutter framework. This app will show all information about some room..
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #cloud_firestore: ^0.13.0+1
  firebase_database: ^3.1.1
  flutter_email_sender: ^2.2.2
  image_picker: ^0.6.3+1
  flutter_masked_text: ^0.8.0
  #flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
